name: Analyze and test

on:
  workflow_call:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  analyze-test:
    name: Analyze and test
    runs-on: ubuntu-latest
    steps:
      # Check out repo
      - uses: actions/checkout@v4

      # Setup node environment
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install client dependencies
      - name: Install client dependencies
        run: npm ci

      # Run eslint
      - name: Run eslint
        run: npm run lint

      # Run unit tests
      - name: Run unit tests
        run: npm run test

      # Run e2e tests using Cypress
      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          start: npm run prod
          wait-on: http://localhost:5173
