name: Analyze and test

on:
  workflow_call:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  analyze-test:
    name: Analyze and test
    runs-on: ubuntu-latest
    steps:
      # Check out repo
      - uses: actions/checkout@v4

      # Setup node environment
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install client dependencies
      - name: Install client dependencies
        run: npm ci

      # Run eslint
      - name: Run eslint
        run: npm run lint
